# Generated by Django 3.0.4 on 2021-07-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0011_auto_20210602_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='page1',
            name='text',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
